#!/bin/bash

# project specific rvm install
export rvm_path=`pwd`/.rvm 
export rvm_ignore_dotfiles=yes

# clear out prior install
rm -rf $rvm_path 

# Install RVM
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 
curl -sSL https://get.rvm.io | bash -s stable 

# Load the rvm environment
source $rvm_path/scripts/rvm

# Install Ruby 2.1.4, bundler, and anything in a possible Gemfile
export ruby_version='2.3.5' # 2.2.1
rvm install $ruby_version 
rvm use $ruby_version
gem install bundler

if test -f "Gemfile"; then bundle install; fi
